## Importing the libraries

In [1]:
## Ignore Warnings

import warnings
warnings.filterwarnings('ignore')

## Numpy and Pandas

import numpy as np
import pandas as pd

## Plotting Libraries

import matplotlib.pyplot as plt
import seaborn as sns

## Importing the datasets

In [2]:
df1 = pd.read_csv('phone_user_review_file_1.csv', encoding='latin-1')
df2 = pd.read_csv('phone_user_review_file_2.csv', encoding='latin-1')
df3 = pd.read_csv('phone_user_review_file_3.csv', encoding='latin-1')
df4 = pd.read_csv('phone_user_review_file_4.csv', encoding='latin-1')
df5 = pd.read_csv('phone_user_review_file_5.csv', encoding='latin-1')
df6 = pd.read_csv('phone_user_review_file_6.csv', encoding='latin-1')

In [3]:
## Merging the datasets

df = df1.append([df2,df3,df4,df5,df6], ignore_index= True)

In [4]:
## Checking the shape of the dataset

df.shape

(1415133, 11)

In [5]:
## Checking the first 10 rows

df.head(10)

phone_url       date lang country            source  \
0  /cellphones/samsung-galaxy-s8/   5/2/2017   en      us  Verizon Wireless   
1  /cellphones/samsung-galaxy-s8/  4/28/2017   en      us       Phone Arena   
2  /cellphones/samsung-galaxy-s8/   5/4/2017   en      us            Amazon   
3  /cellphones/samsung-galaxy-s8/   5/2/2017   en      us           Samsung   
4  /cellphones/samsung-galaxy-s8/  5/11/2017   en      us  Verizon Wireless   
5  /cellphones/samsung-galaxy-s8/  5/10/2017   en      us  Verizon Wireless   
6  /cellphones/samsung-galaxy-s8/  5/10/2017   en      us  Verizon Wireless   
7  /cellphones/samsung-galaxy-s8/  5/10/2017   en      us  Verizon Wireless   
8  /cellphones/samsung-galaxy-s8/  5/10/2017   en      us  Verizon Wireless   
9  /cellphones/samsung-galaxy-s8/  5/10/2017   en      us  Verizon Wireless   

                domain  score  score_max  \
0  verizonwireless.com   10.0       10.0   
1       phonearena.com   10.0       10.0   
2           amazon.com    6.0       10.0   
3          samsung.com    9.2       10.0   
4  verizonwireless.com    4.0       10.0   
5  verizonwireless.com   10.0       10.0   
6  verizonwireless.com    4.0       10.0   
7  verizonwireless.com    6.0       10.0   
8  verizonwireless.com    6.0       10.0   
9  verizonwireless.com    8.0       10.0   

                                             extract           author  \
0  As a diehard Samsung fan who has had every Sam...       CarolAnn35   
1  Love the phone. the phone is sleek and smooth ...        james0923   
2  Adequate feel. Nice heft. Processor's still sl...         R. Craig   
3  Never disappointed. One of the reasons I've be...      Buster2020    
4  I've now found that i'm in a group of people t...       S Ate Mine   
5  I am the type of person who never would comple...            BDB76   
6  The way this Samsung S8 phone operates is more...         KLC30306   
7  I bought this phone very excited to use it. I ...             Mnhy   
8  It is an extremely advanced and truly a Smart ...          Mr Alan   
9  Great phone with a PHENOMENAL Camera, not all ...  Raven Wolf Song   

                                             product  
0                                  Samsung Galaxy S8  
1                                  Samsung Galaxy S8  
2  Samsung Galaxy S8 (64GB) G950U 5.8" 4G LTE Unl...  
3                      Samsung Galaxy S8 64GB (AT&T)  
4                                  Samsung Galaxy S8  
5                                  Samsung Galaxy S8  
6                                  Samsung Galaxy S8  
7                                  Samsung Galaxy S8  
8                                  Samsung Galaxy S8  
9                                  Samsung Galaxy S8

In [6]:
## Checking the last ten rows

df.tail(10)

phone_url       date lang country source  \
1415123  /cellphones/alcatel-ot-club_1187/  5/25/2000   de      de   Ciao   
1415124  /cellphones/alcatel-ot-club_1187/  5/21/2000   de      de   Ciao   
1415125  /cellphones/alcatel-ot-club_1187/  5/21/2000   de      de   Ciao   
1415126  /cellphones/alcatel-ot-club_1187/  5/20/2000   de      de   Ciao   
1415127  /cellphones/alcatel-ot-club_1187/  5/19/2000   de      de   Ciao   
1415128  /cellphones/alcatel-ot-club_1187/  5/12/2000   de      de   Ciao   
1415129  /cellphones/alcatel-ot-club_1187/  5/11/2000   de      de   Ciao   
1415130  /cellphones/alcatel-ot-club_1187/   5/4/2000   de      de   Ciao   
1415131  /cellphones/alcatel-ot-club_1187/   5/1/2000   de      de   Ciao   
1415132  /cellphones/alcatel-ot-club_1187/  4/25/2000   de      de   Ciao   

          domain  score  score_max  \
1415123  ciao.de    8.0       10.0   
1415124  ciao.de    8.0       10.0   
1415125  ciao.de    8.0       10.0   
1415126  ciao.de    4.0       10.0   
1415127  ciao.de    2.0       10.0   
1415128  ciao.de    2.0       10.0   
1415129  ciao.de   10.0       10.0   
1415130  ciao.de    2.0       10.0   
1415131  ciao.de    8.0       10.0   
1415132  ciao.de    2.0       10.0   

                                                   extract        author  \
1415123  Vor ein paar Monaten bekam ich das Alcatel Clu...        abruna   
1415124  Das Handy kann man einfacher bedienen als eine...  Villeneuve99   
1415125  Wem Design nicht so wichtig ist, der sollte si...          Larz   
1415126  Wenn ich das Club von Alcatel in der Hand habe...      BBC_NEWS   
1415127  Als langjÃ¤hriger Handybesitzer und -nutzer, n...        anjuli   
1415128  Weil mein Onkel bei ALcatel arbeitet habe ich ...    david.paul   
1415129  Hy Liebe Leserinnen und Leser!! Ich habe seit ...  Christiane14   
1415130  Jetzt hat wohl Alcatell gedacht ,sie machen wa...    michaelawr   
1415131  Ich bin seit 2 Jahren (stolzer) Besitzer eines...   claudia0815   
1415132  Was sich Alkatel hier wieder ausgedacht hat,sc...    michaelawr   

                         product  
1415123  Alcatel Club Plus Handy  
1415124  Alcatel Club Plus Handy  
1415125  Alcatel Club Plus Handy  
1415126  Alcatel Club Plus Handy  
1415127  Alcatel Club Plus Handy  
1415128  Alcatel Club Plus Handy  
1415129  Alcatel Club Plus Handy  
1415130  Alcatel Club Plus Handy  
1415131  Alcatel Club Plus Handy  
1415132  Alcatel Club Plus Handy

In [7]:
## Rounding off score to nearest integer

df.score = df.score.round()

#### Checking for NULL values of score

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1415133 entries, 0 to 1415132
Data columns (total 11 columns):
 #   Column     Non-Null Count    Dtype  
---  ------     --------------    -----  
 0   phone_url  1415133 non-null  object 
 1   date       1415133 non-null  object 
 2   lang       1415133 non-null  object 
 3   country    1415133 non-null  object 
 4   source     1415133 non-null  object 
 5   domain     1415133 non-null  object 
 6   score      1351644 non-null  float64
 7   score_max  1351644 non-null  float64
 8   extract    1395772 non-null  object 
 9   author     1351931 non-null  object 
 10  product    1415132 non-null  object 
dtypes: float64(2), object(9)
memory usage: 118.8+ MB


#### Imputing missing values

In [9]:
df.score.median()

9.0

In [10]:
df.score = df.score.replace(np.nan,9)
df.score_max = df.score_max.replace(np.nan,10)

In [11]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1415133 entries, 0 to 1415132
Data columns (total 11 columns):
 #   Column     Non-Null Count    Dtype  
---  ------     --------------    -----  
 0   phone_url  1415133 non-null  object 
 1   date       1415133 non-null  object 
 2   lang       1415133 non-null  object 
 3   country    1415133 non-null  object 
 4   source     1415133 non-null  object 
 5   domain     1415133 non-null  object 
 6   score      1415133 non-null  float64
 7   score_max  1415133 non-null  float64
 8   extract    1395772 non-null  object 
 9   author     1351931 non-null  object 
 10  product    1415132 non-null  object 
dtypes: float64(2), object(9)
memory usage: 118.8+ MB


In [12]:
## Removing duplicates

df = df.drop_duplicates()

In [13]:
## Keeping on 1000000 rows

df = df.dropna()
df = df.sample(n = 1000000, random_state=612)

In [14]:
## Dropping irrelevant features

df.drop(['phone_url','score_max'], axis = 1, inplace=True)

## Kept the features like lang, country, date, source, domain, extract as they may come in handy later. They can be dropped later if not required.
## Kept Author, Product and Score as advised.

In [15]:
## Most Rated Products

print(*df['product'].value_counts()[0:10].index.values, sep = '\n')

Lenovo Vibe K4 Note (White,16GB)
Lenovo Vibe K4 Note (Black, 16GB)
OnePlus 3 (Graphite, 64 GB)
OnePlus 3 (Soft Gold, 64 GB)
Huawei P8lite zwart / 16 GB
Samsung Galaxy Express I8730
Lenovo Vibe K5 (Gold, VoLTE update)
Samsung Galaxy S6 zwart / 32 GB
Lenovo Vibe K5 (Grey, VoLTE update)
Lenovo Used Lenovo Zuk Z1 (Space Grey, 64GB)


In [16]:
## Users with most reviews

print(*df['author'].value_counts()[0:20].index.values, sep = '\n') 

## taking a larger list as some users are generic users with names such as amazon customer, anonymous or a customer in different languages and other names are not readable

Amazon Customer
Cliente Amazon
e-bit
Client d'Amazon
Amazon Kunde
Anonymous
einer Kundin
einem Kunden
unknown
Anonymous 
David
ÐÐ»ÐµÐºÑÐ°Ð½Ð´Ñ
Alex
Ð¡ÐµÑÐ³ÐµÐ¹
Marco
Andrea
ÐÐ¼Ð¸ÑÑÐ¸Ð¹
ÐÐ½Ð´ÑÐµÐ¹
Daniel
ÐÐ»ÐµÐºÑÐµÐ¹


#### Only discernible names that come from the above list are: David, Alex, Marco, Andrea and Daniel

In [17]:
## Products with more than 50 reviews

lst = df['product'].value_counts()[df['product'].value_counts()>50].index
dfpro50 = df.query('product in @lst')

In [18]:
## Users with more than 50 ratings

lst2 = df['author'].value_counts()[df['author'].value_counts()>50].index
dfusr50 = df.query('author in @lst2')

In [19]:
## Merging the two dataframes

new_df = dfpro50.merge(dfusr50, how='outer' )
print('Shape of the dataframe that has users with more than 50 ratings and products with more than 50 ratings is',new_df.shape)


Shape of the dataframe that has users with more than 50 ratings and products with more than 50 ratings is (628802, 9)


## Building a popularity based model

In [20]:
## Converting date column to datetime format and selecting only the ratings since 2017 because ---
## --- mobile phones become outdated in 2 years

new_df['date'] = pd.to_datetime(new_df['date'])
pop_reco_df = new_df[new_df['date']>'2017-01-01']

In [21]:
## picking up mobile phones with atleast 200 ratings since popularity will not only depend on average ratings but also on ---
## --- the number of ratings given

lst3 = pop_reco_df['product'].value_counts()[pop_reco_df['product'].value_counts()>=200].index.values
pop_reco_df = pop_reco_df.query('product in @lst3')

In [22]:
## Final recommendation of five most popular phones

pop_reco_df.groupby('product')['score'].mean().sort_values(ascending = False).head()

product
Apple iPhone 7 4,7" 32 GB                                                                              9.768707
Apple iPhone 7 Plus 5,5" 128 GB                                                                        9.754386
Samsung Galaxy S7 Smartphone, 12,9 cm (5,1 Zoll) Display, LTE (4G)                                     9.707317
Huawei P9 Lite Dual-SIM Smartphone, 13,2 cm (5,2 Zoll) Display, LTE (4G), Android 6.0 (Marshmallow)    9.689655
Samsung Galaxy S7 edge Smartphone, 13,9 cm (5,5 Zoll) Display, LTE (4G)                                9.670051
Name: score, dtype: float64

In [23]:
## Printing just the names

print(*pop_reco_df.groupby('product')['score'].mean().sort_values(ascending = False).head().index, sep = '\n')

Apple iPhone 7 4,7" 32 GB
Apple iPhone 7 Plus 5,5" 128 GB
Samsung Galaxy S7 Smartphone, 12,9 cm (5,1 Zoll) Display, LTE (4G)
Huawei P9 Lite Dual-SIM Smartphone, 13,2 cm (5,2 Zoll) Display, LTE (4G), Android 6.0 (Marshmallow)
Samsung Galaxy S7 edge Smartphone, 13,9 cm (5,5 Zoll) Display, LTE (4G)


## Building a collaborative model with SVD and KNNwithMeans 

In [24]:
## Laoding the required libraries

from surprise import SVD
from surprise import KNNWithMeans
from surprise import Dataset
from surprise import accuracy
from surprise import Reader
from surprise.model_selection import train_test_split

In [25]:
## Reducing size of database based on latest ratings only (from 1st Jan 2017). 
## Here we can also choose the dataset with products with atleast 50 ratings and users with atleast 50 ratings.
## I chose the larger dataset and filtered from there (since after multiple iterations final model accuracy was better for entire dataset) )

df['date'] = pd.to_datetime(df['date'])
usable_df = df[df['date']>'2017-01-01']

In [26]:
usable_df.shape

(36007, 9)

In [27]:
## Loading dataset from df to surprise library usable form

reader = Reader(rating_scale=(0, 10))
data = Dataset.load_from_df(usable_df[['author','product','score']], reader)
trainset, testset = train_test_split(data, test_size=.15, random_state=42)

In [28]:
## Fitting the SVD model

model1 = SVD()
model1.fit(trainset)

In [29]:
## Predictions with SVD model

model1_test_pred = model1.test(testset)

In [30]:
## Displaying predictions

model1_test_pred

[Prediction(uid='Cez T', iid='Apple iPhone SE, 64Gb - Rose Gold', r_ui=10.0, est=8.575334628217988, details={'was_impossible': False}),
 Prediction(uid='Ð\xadÐ»ÐµÐ½', iid='Apple iPhone 7 Plus 32GB (Ð·Ð¾Ð»Ð¾Ñ\x82Ð¸Ñ\x81Ñ\x82Ñ\x8bÐ¹)', r_ui=9.0, est=8.464059853680801, details={'was_impossible': False}),
 Prediction(uid='Amazon Customer', iid='Honor 6X (Silver, 32GB)', r_ui=10.0, est=7.6758216284175935, details={'was_impossible': False}),
 Prediction(uid='Amazon Customer', iid='OnePlus 3T (Soft Gold, 6GB RAM + 64GB memory)', r_ui=10.0, est=7.654361414015278, details={'was_impossible': False}),
 Prediction(uid='e-bit', iid='Smartphone Apple iPhone 7 32GB', r_ui=10.0, est=9.477672521542072, details={'was_impossible': False}),
 Prediction(uid='Gaurav Jingala', iid='OnePlus 3T (Soft Gold, 6GB RAM + 64GB memory)', r_ui=10.0, est=8.582866409106757, details={'was_impossible': False}),
 Prediction(uid='JJ', iid='Motorola MOTO Z PLAY (32GB) 5.5" - 4G LTE Factory Unlocked GSM (International Model) 

In [31]:
## getting RMSE for SVD Model


print("SVD Model : Test Set")
accuracy.rmse(model1_test_pred, verbose=True)

SVD Model : Test Set
RMSE: 2.3869


2.3869290134191754

In [32]:
## Fitting the KNNwithMeans model (user based collab)

model2 = KNNWithMeans(k=50, sim_options={'name': 'pearson_baseline', 'user_based': True})
model2.fit(trainset)

Estimating biases using als...
Computing the pearson_baseline similarity matrix...
Done computing similarity matrix.


In [33]:
## Predictions with KNNwithMeans model (user based collab)

model2_test_pred = model2.test(testset)

In [34]:
## Displaying predictions

model2_test_pred

[Prediction(uid='Cez T', iid='Apple iPhone SE, 64Gb - Rose Gold', r_ui=10.0, est=8.443064858683222, details={'was_impossible': True, 'reason': 'User and/or item is unknown.'}),
 Prediction(uid='Ð\xadÐ»ÐµÐ½', iid='Apple iPhone 7 Plus 32GB (Ð·Ð¾Ð»Ð¾Ñ\x82Ð¸Ñ\x81Ñ\x82Ñ\x8bÐ¹)', r_ui=9.0, est=9.0, details={'actual_k': 0, 'was_impossible': False}),
 Prediction(uid='Amazon Customer', iid='Honor 6X (Silver, 32GB)', r_ui=10.0, est=7.76, details={'actual_k': 50, 'was_impossible': False}),
 Prediction(uid='Amazon Customer', iid='OnePlus 3T (Soft Gold, 6GB RAM + 64GB memory)', r_ui=10.0, est=7.919999999999999, details={'actual_k': 50, 'was_impossible': False}),
 Prediction(uid='e-bit', iid='Smartphone Apple iPhone 7 32GB', r_ui=10.0, est=9.5, details={'actual_k': 16, 'was_impossible': False}),
 Prediction(uid='Gaurav Jingala', iid='OnePlus 3T (Soft Gold, 6GB RAM + 64GB memory)', r_ui=10.0, est=8.443064858683222, details={'was_impossible': True, 'reason': 'User and/or item is unknown.'}),
 Predicti

In [35]:
## getting RMSE for KNNwithMeans model (user based collab)


print("User based Model : Test Set")
accuracy.rmse(model2_test_pred, verbose=True)

User based Model : Test Set
RMSE: 2.5604


2.5603607503783214

In [36]:
## Fitting the KNNwithMeans model (item based collab)

model3 = KNNWithMeans(k=50, sim_options={'name': 'pearson_baseline', 'user_based': False})
model3.fit(trainset)

Estimating biases using als...
Computing the pearson_baseline similarity matrix...
Done computing similarity matrix.


In [37]:
## Predictions with KNNwithMeans model (item based collab)

model3_test_pred = model3.test(testset)

In [38]:
## Displaying predictions

model3_test_pred

[Prediction(uid='Cez T', iid='Apple iPhone SE, 64Gb - Rose Gold', r_ui=10.0, est=8.443064858683222, details={'was_impossible': True, 'reason': 'User and/or item is unknown.'}),
 Prediction(uid='Ð\xadÐ»ÐµÐ½', iid='Apple iPhone 7 Plus 32GB (Ð·Ð¾Ð»Ð¾Ñ\x82Ð¸Ñ\x81Ñ\x82Ñ\x8bÐ¹)', r_ui=9.0, est=9.0, details={'actual_k': 1, 'was_impossible': False}),
 Prediction(uid='Amazon Customer', iid='Honor 6X (Silver, 32GB)', r_ui=10.0, est=7.760000000000001, details={'actual_k': 50, 'was_impossible': False}),
 Prediction(uid='Amazon Customer', iid='OnePlus 3T (Soft Gold, 6GB RAM + 64GB memory)', r_ui=10.0, est=7.92, details={'actual_k': 50, 'was_impossible': False}),
 Prediction(uid='e-bit', iid='Smartphone Apple iPhone 7 32GB', r_ui=10.0, est=9.540331989551055, details={'actual_k': 50, 'was_impossible': False}),
 Prediction(uid='Gaurav Jingala', iid='OnePlus 3T (Soft Gold, 6GB RAM + 64GB memory)', r_ui=10.0, est=8.443064858683222, details={'was_impossible': True, 'reason': 'User and/or item is unknown.

In [39]:
## getting RMSE for KNNwithMeans model (item based collab)


print("Item based Model : Test Set")
accuracy.rmse(model3_test_pred, verbose=True)

Item based Model : Test Set
RMSE: 2.4892


2.4891970617442074

In [40]:
## Transferring test predictions from SVD Model to a dataframe

testusers_df = pd.DataFrame(model1_test_pred)

In [41]:
## Average rating for test users

testusers_df.est.mean()

8.464493094797332

## Findings and Inferences

1. Amongst the Collaborative models SVD model performs the best in terms of accuracy with minimum RMSE of 2.39 vs 2.49 of item based model and 2.56 of user based model
2. In terms of time taken to run: item based model is much faster than the other two models followed by SVD and user based model (slowest)
3. As such the difference in rating estimations between the two KNNwithMeans models is not very high but item based model performs better (more accurate) as well as works faster.

## Recommending top 5 products for test users

In [42]:
## creating a new testset to get predictions for test users on all products in the test set

users_array = testusers_df.uid.unique()
items_array = testusers_df.iid.unique()
newtestset = []
for i in users_array:
    for j in items_array:
        x = (i,j,0)
        newtestset.append(x)

In [43]:
## Predicting the ratings for each product for each user

new_test_pred = model3.test(newtestset)
new_test_pred_df = pd.DataFrame(new_test_pred)

In [44]:
## Getting the top five recommendations for 25 users. Limiting it to 25 to save runtime

new_test_pred_df = new_test_pred_df.sort_values('est',ascending = False)
recommendation = []
c=0
for i in users_array[0:25]:
    a = new_test_pred_df[new_test_pred_df['uid']==i].head().iid.values
    y = [i,a[0],a[1],a[2],a[3],a[4]]
    recommendation.append(y)

In [45]:
## Displaying recommendations in a dataframe

reco_df = pd.DataFrame(recommendation,columns = ['UserName','Reco1','Reco2','Reco3','Reco4','Reco5'])
reco_df

UserName                                              Reco1  \
0             Cez T                  Apple iPhone SE, 64Gb - Rose Gold   
1          Ð­Ð»ÐµÐ½  iPhone 6s Apple com Tela 4,7â HD, 32GB, 3D T...   
2   Amazon Customer     Ð¡Ð¾ÑÐ¾Ð²ÑÐ¹ ÑÐµÐ»ÐµÑÐ¾Ð½ Huawei Nova Plus   
3             e-bit                                 Lenovo Zuk Z1 64GB   
4    Gaurav Jingala  Sim Free Samsung Galaxy S7 Edge Mobile Phone -...   
5                JJ             HTC U Ultra Smart Phone, Sapphire Blue   
6            Froggy  ASUS Zenfone 3 (ZE520KL) Smartphone Â»13,2 cm ...   
7               Rle  Asus Used Asus Zenfone Selfie ZD551KL-2A506IN ...   
8      Miraakkeli81                                  VIVO Y51L (Black)   
9    Prabhat Pandey  HUAWEI Honor 7 Lite Dual-SIM 16 GB Ã¤lypuhelin...   
10          Thibaut  Microsoft Lumia 640 Smartphone, 8 GB, Marchio ...   
11     Amazon Kunde                                 Lenovo Zuk Z1 64GB   
12  Client d'Amazon                      Alcatel PIXI 4 (5) wit / 8 GB   
13   clemens van Os  Jiayu ÐÐ¾Ð±Ð¸Ð»ÑÐ½ÑÐ¹ ÑÐµÐ»ÐµÑÐ¾Ð½ Jiayu G4S   
14  Raymond Exaltus  Huawei Honor 7 Lite Dual-SIM âAndroid-puheli...   
15            Dario  Lumia 435 Microsoft Lumia 435 smartphone T-Mob...   
16   Cliente Amazon  WIKO Fever SE - Smartphone sbloccato 4G, scher...   
17           Werner  DOOGEE X5 Max Pro Smartphone, 5 Pollici HD IPS...   
18            Maria  DOOGEE X5 Max Pro Smartphone, Android 6.0 4G S...   
19             Sepp  Microsoft ÐÐ¾Ð±Ð¸Ð»ÑÐ½ÑÐ¹ ÑÐµÐ»ÐµÑÐ¾Ð½ Mi...   
20         Giovanni                     SAMSUNG GALAXY A3 (2017) BLACK   
21      rajiv kumar           ZTE Blade V7 lite (Ð·Ð¾Ð»Ð¾ÑÐ¸ÑÑÑÐ¹)   
22      Frank MÃ¼ns  Samsung Galaxy J5 Smartphone (5 Zoll (12,7 cm)...   
23            Susan                  Apple iPhone SE, 32Gb - Rose Gold   
24    Edee Campbell                       Apple iPhone 7, 32Gb - Black   

                                                Reco2  \
0               Kyocera Milano Android Phone (Sprint)   
1   Sony Xperia XCompact Smartphone (11,7 cm (4,6 ...   
2   Samsung Galaxy S7 SM-G930F 32GB Factory Unlock...   
3   DOOGEE X5 Max Pro Smartphone, Android 6.0 4G S...   
4       Nokia 230 Smartphone, Dual SIM, Nero [Italia]   
5              Huawei Honor 6X (Ð·Ð¾Ð»Ð¾ÑÐ¸ÑÑÑÐ¹)   
6   Lenovo ÐÐ¾Ð±Ð¸Ð»ÑÐ½ÑÐ¹ ÑÐµÐ»ÐµÑÐ¾Ð½ Lenov...   
7                                   Google Pixel 32GB   
8   Smartphone Samsung Galaxy S7 Edge G935F, Octa ...   
9                                   Google Pixel 32GB   
10  Sony Xperia SP Smartphone (11,7 cm (4,6 Zoll) ...   
11  DOOGEE X5 Max Pro Smartphone, Android 6.0 4G S...   
12  Samsung Galaxy A5 (2017) SM-A520F/DS 32GB Blue...   
13                  Sony Xperia XA Smartphone (svart)   
14  iPOMCASE COQUE ETUI POCHETTE HOUSSE FOLIO FENÃ...   
15   Samsung Galaxy S III Smartphone, Bianco [Italia]   
16  Honor 3C Smartphone, Dual SIM, Display 5 Polli...   
17  Samsung Galaxy S4 Smartphone (5 Zoll (12,7 cm)...   
18  Samsung Galaxy A5 (2017) SM-A520F/DS 32GB Blue...   
19  Huawei P9 lite Smartphone (13,2 cm (5,2 Zoll) ...   
20  Samsung Galaxy S8+ âAndroid-puhelin 64 Gt, M...   
21                              Smartphone LG K4 K130   
22  Huawei P9 Lite Smartphone, LTE, Display 5,2â...   
23  Huawei Honor 7 Lite dual-sim smarttelefon 16 G...   
24             Sony Xperia Z5 Premium Dual (Ñ
ÑÐ¾Ð¼)   

                                                Reco3  \
0                    SAMSUNG GALAXY J7 2016 BLACK+SIM   
1   IBROZ ASUS ZenFone 3 ZE520KL (5.2") Etui Porte...   
2         Apple iPhone 7 Plus 32 Gt âpuhelin, kulta   
3                       Alcatel PIXI 4 (5) wit / 8 GB   
4                          Microsoft Nokia 3210 Handy   
5         Sim Free iPhone 7 128GB Mobile Phone - Gold   
6   Samsung Straight Talk Samsung Galaxy S5 "Elect...   
7                   Sony Xperia Z5 Smartphone (svart)   
8              Apple iPhone 7 Plus, 256Gb - Jet Black   
9                   Sony Xperia Z

In [46]:
## Using crossvalidation to improve prediction accuracy

from surprise.model_selection import cross_validate
results1 = cross_validate(model1, data, measures=['RMSE'], cv=3, verbose=False)
results2 = cross_validate(model2, data, measures=['RMSE'], cv=3, verbose=False)
results3 = cross_validate(model3, data, measures=['RMSE'], cv=3, verbose=False)

Estimating biases using als...
Computing the pearson_baseline similarity matrix...
Done computing similarity matrix.
Estimating biases using als...
Computing the pearson_baseline similarity matrix...
Done computing similarity matrix.
Estimating biases using als...
Computing the pearson_baseline similarity matrix...
Done computing similarity matrix.
Estimating biases using als...
Computing the pearson_baseline similarity matrix...
Done computing similarity matrix.
Estimating biases using als...
Computing the pearson_baseline similarity matrix...
Done computing similarity matrix.
Estimating biases using als...
Computing the pearson_baseline similarity matrix...
Done computing similarity matrix.


In [47]:
print('improved and robust accuracy measure of SVD based model =', round(results1['test_rmse'].mean(),2),'compared to 2.39 earlier')
print('improved and robust accuracy measure of user based model =', round(results2['test_rmse'].mean(),2),'compared to 2.56 earlier')
print('improved and robust accuracy measure of item based model =', round(results3['test_rmse'].mean(),2),'compared to 2.49 earlier')

improved and robust accuracy measure of SVD based model = 2.35 compared to 2.39 earlier
improved and robust accuracy measure of user based model = 2.5 compared to 2.56 earlier
improved and robust accuracy measure of item based model = 2.47 compared to 2.49 earlier


#### Question: Business Scenario for popularity based recommendation systems:

#### Answer: Where user's ratings data for other items is not available or or a new user is identified

#### Question: Business Scenario for CF based recommendation systems:

#### Answer: Where user's historical rating data for other items is available and rating data for each item from some other users is available

#### Question: Other methods to improve recommendations for different users

#### Answer: 1. Content Based filtering methods using the extract and product columns and 2. Deep Neural Nets